import test from 'node:test';import assert from 'node:assert/strict';
import {decodeTelemetry,decodeSettings,encodeCommand,sequenceGap,samplesInWindow} from '../protocol.js';
import {acknowledgement,defaults} from './fixtures.js';
export function packet(version=4){const size=version===1?124:version===2?164:version===3?176:140,v=new DataView(new ArrayBuffer(size));v.setUint8(0,69);v.setUint8(1,90);v.setUint8(2,version);v.setUint8(3,size);v.setUint32(4,42,true);v.setUint16(14,1023,true);v.setUint16(18,3,true);for(let i=0;i<(size-20)/4;i++)v.setFloat32(20+4*i,i+.25,true);return v;}
test('decodes compact MCU flight and g-force values',()=>{const s=decodeTelemetry(packet());assert.equal(s.gForce,3.25);assert.equal(s.vario,17.25);assert.equal(s.altitude,19.25);assert.equal(s.speedSigma,26.25);assert.equal(s.status,3);assert.equal(s.linearE,undefined);});
test('legacy packets retain raw sensors but no browser vario',()=>{const s=decodeTelemetry(packet(1));assert.equal(s.pressure,16.25);assert.ok(Number.isNaN(s.vario));assert.equal(s.status,0);});
test('rejects truncated and unsupported data',()=>{assert.throws(()=>decodeTelemetry(new ArrayBuffer(20)),/Paketkennung/);const v=packet();v.setUint8(2,8);assert.throws(()=>decodeTelemetry(v),/Protokollversion/);assert.throws(()=>decodeTelemetry(new DataView(packet().buffer,0,100)),/Paketlänge/);});
test('settings encode and acknowledgements preserve request identity',()=>{const v=acknowledgement(32);const r=decodeSettings(v);assert.equal(r.request,32);assert.equal(r.qnh,1013.25);assert.equal(r.pitch8,2400);assert.ok(Math.abs(r.responseTau-.55)<1e-6);assert.throws(()=>decodeSettings(new ArrayBuffer(20)));assert.throws(()=>decodeSettings(encodeCommand(5,32)));assert.throws(()=>decodeSettings(acknowledgement(1,{...defaults,qnh:0})));});
test('v3 remains readable and carries MCU audio parameters',()=>{const v=packet(3);v.setFloat32(164,870,true);v.setFloat32(168,.5,true);v.setFloat32(172,.22,true);const s=decodeTelemetry(v);assert.equal(s.toneHz,870);assert.equal(s.tonePeriod,.5);});
test('known altitude command carries the calibration height',()=>{const v=new DataView(encodeCommand(8,7,{calibrationAltitude:642}));assert.equal(v.getFloat32(8,true),642);});
test('sequence gaps and final 60 seconds',()=>{assert.equal(sequenceGap(0xffffffff,1),1);assert.equal(sequenceGap(8,8),0);assert.equal(sequenceGap(8,1),0);assert.deepEqual(samplesInWindow([{received:39999},{received:40000},{received:100000}],100000).map(x=>x.received),[40000,100000]);});
