// Playback only: pitch, cadence and thresholds are generated by the Nicla.
export class VarioAudio {
  constructor(Context=globalThis.AudioContext||globalThis.webkitAudioContext){this.Context=Context;this.enabled=false;this.volume=.75;this.mode=0;this.phase=0;this.lastTime=0;this.period=0;}
  async enable(){
    if(!this.Context)throw Error('Audiowiedergabe wird in diesem Browser nicht unterstützt.');
    if(!this.context){
      this.context=new this.Context();this.gain=this.context.createGain();this.osc=this.context.createOscillator();
      this.osc.type='sine';this.gain.gain.value=0;this.osc.connect(this.gain);this.gain.connect(this.context.destination);this.osc.start();
    }
    // Must be invoked directly from a tap to unlock audio on iOS / Bluefy.
    await this.context.resume();
    if(this.context.state!=='running')throw Error('Ton wurde vom Browser blockiert. Erneut einschalten.');
    this.enabled=true;this.mode=0;this.phase=0;this.lastTime=this.context.currentTime;
  }
  mute(){
    if(!this.context)return;
    const t=this.context.currentTime,g=this.gain.gain;
    g.cancelScheduledValues(t);g.setTargetAtTime(0,t,.004);this.mode=0;this.phase=0;this.lastTime=t;
  }
  disable(){this.enabled=false;this.mute();}
  setVolume(value){this.volume=Math.min(1,Math.max(0,Number(value)||0));if(this.context)this.mute();}
  render(tone,fresh){
    if(!this.enabled||!this.context)return;
    if(this.context.state!=='running'){this.disable();return;}
    const hz=tone?.toneHz,period=tone?.tonePeriod,on=tone?.toneOn;
    if(!fresh||!Number.isFinite(hz)||hz<80||hz>2500||!Number.isFinite(period)||period<0||period>2.501||!Number.isFinite(on)||on<0||on>period||(period>0&&(period<.079||on<.039))){this.mute();return;}
    const t=this.context.currentTime,g=this.gain.gain,mode=period===0?-1:1,level=this.volume*.18;
    this.osc.frequency.setTargetAtTime(hz,t,.025);
    if(mode!==this.mode){this.mute();this.mode=mode;}
    if(mode===-1){
      // Renew a short audio-clock lease. Even if JavaScript is suspended, the
      // sink tone fades automatically rather than hanging indefinitely.
      g.cancelScheduledValues(t);g.setTargetAtTime(level,t,.008);
      g.setTargetAtTime(0,t+.22,.008);return;
    }
    if(this.period>0)this.phase=((this.phase+t-this.lastTime)%this.period)/this.period*period;
    this.period=period;this.lastTime=t;
    const envelope=p=>p>=on?0:Math.max(0,Math.min(1,p/.008,(on-p)/.008));
    g.cancelScheduledValues(t);g.setValueAtTime(level*envelope(this.phase),t);
    // Render only a short lease in audio-clock time. Preserve phase across BLE
    // packets and render ticks; the full configured pulse length remains intact.
    for(let d=.004;d<=.24;d+=.004)g.linearRampToValueAtTime(level*envelope((this.phase+d)%period),t+d);
    g.linearRampToValueAtTime(0,t+.25);
  }
  test(){
    if(!this.enabled||this.context?.state!=='running')return;
    const t=this.context.currentTime,g=this.gain.gain;this.mute();
    this.osc.frequency.setValueAtTime(800,t);g.setValueAtTime(0,t);
    g.linearRampToValueAtTime(this.volume*.18,t+.01);g.setValueAtTime(this.volume*.18,t+.2);g.linearRampToValueAtTime(0,t+.22);
  }
}
